### ISSUE TITLE
Release 4.1.x (master)

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#1190]
Proposing to freeze the master branch to 4.1.x.

  - [x] resolve caj/pvmanager issue #1174
  - [x] create diag feature to prevent inclusion of duplication versions of applications like probe and pvtree
  - [x] python scripts take significantly longer to load #1197
  - [x] NPE for xyGraph #1200 #1199
  - [x] report BOY regression tests (ControlSystemStudio/opi-regression-tests)
     https://docs.google.com/forms/d/1cKILK51oWpVcy5iDCe4gPK6mvCSvlMWIS5JazuO2_Lc/viewform
  - [x] make 4.1.x branch
  - [x] make new github milestone 4.2.0 - testing (master)
  - [x] make new github milestone 4.1.1 - stable (4.1.x branch)
  - [x] make Jenkins csstudio.product release
  - [x] run Jenkins csstudio.product release

Site Representatives, are there any other outstanding issues that need to be addressed before release of 4.1.x?
@berryma4, @kasemir, @shroffk, @richardfearn, @willrogers, @utzeln, @mjclarke01, @jpenning, @ksdj

**Comment by jpenning** [comment]
We're fine with this, keep up the good work :-)

Jörg.

On 09.06.2015 15:46, Eric Berryman wrote:
>
> Proposing to freeze the master branch to 4.1.x.
>
>   * resolve caj/pvmanager issue #1174
>     <https://github.com/ControlSystemStudio/cs-studio/issues/1174>
>   * report BOY regression tests
>     (ControlSystemStudio/opi-regression-tests)
>     https://docs.google.com/forms/d/1cKILK51oWpVcy5iDCe4gPK6mvCSvlMWIS5JazuO2_Lc/viewform
>
>   * make 4.1.x branch
>   * make new github milestone 4.2.0 - testing (master)
>   * make new github milestone 4.1.1 - stable (4.1.x branch)
>   * make / run Jenkins csstudio.product release
>
> Site Representatives, are there any other outstanding issues that need 
> to be addressed before release of 4.1.x?
> @berryma4 <https://github.com/berryma4>, @kasemir 
> <https://github.com/kasemir>, @shroffk <https://github.com/shroffk>, 
> @richardfearn <https://github.com/richardfearn>, @willrogers 
> <https://github.com/willrogers>, @utzeln <https://github.com/utzeln>, 
> @mjclarke01 <https://github.com/mjclarke01>, @jpenning 
> <https://github.com/jpenning>, @ksdj <https://github.com/ksdj>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ControlSystemStudio/cs-studio/issues/1190>.
>

-- 
------------------------------------------------------------------------
Jörg Penning                             Cryogenic Controls Group(MKS-2)
phone:  +49-40-8998-2741                Deutsches Elektronen Synchrotron
fax:    +49-40-8994-3256                                    Notkestr. 85
e-mail: Joerg.Penning@desy.de                              22607 Hamburg
WWW-MKS2.desy.de                                                 Germany
------------------------------------------------------------------------

**Comment by kasemir** [comment]
Yes. Any chance to actually resolve the caj/pvmanager issue?

**Comment by shroffk** [comment]
I am still working on this.

**Comment by willrogers** [comment]
Fine for me.  Thanks!

**Comment by mjclarke01** [comment]
Fine with us.
Thanks,
Matt

**Comment by shroffk** [comment]
For Issue #1174 I have submitted a fix, this prevents the deadlock. However that are other issues with this solution which are exacerbated with by the way the current linking container handles connections.
Should this be marked off?

**Comment by berryma4** [comment]
The caj/pvamanager issue is "relieved" now that the linking container was reverted to a similar past state, of not trying to to keep connections (widget connections, not pvmanager connections) between widgets inside to outside of linking containers.

**Comment by berryma4** [comment]
next step is to report the boy validation tests and branch
(then run product release)

**Comment by berryma4** [comment]
https://docs.google.com/forms/d/1cKILK51oWpVcy5iDCe4gPK6mvCSvlMWIS5JazuO2_Lc/viewanalytics

| Test       | Result           |
| ------------- |:-------------:|
| timestamp | 6/25/2015 13:54:39 |
| issue ticket | https://github.com/ControlSystemStudio/cs-studio/issues/1190 |
| Tester | Berryman |
| __BOY Examples__ |
| All BOY Examples | Pass |
| __Issues__ |
| Issue 1081 | Pass |
| Issue 1103 | Pass |
| Issue 1197 | Pass |
| __Performance Tests__ |
| graph_performance_test.opi  | Pass |
| large_led_performace_test.opi | Pass |
| small_led_performace_test.opi | Pass |
| tank_performace_test.opi | Pass |
| test_update_performance_test.opi.opi | Pass |
| l__Rules Tests__ |
| General_rule.opi | Pass |
| Graphs_rule.opi | Pass |
| LED_color_rule.opi | Pass |
| Label_rule.opi | Pass |
| Switch_rule.opi | Pass |
| __WidgetTests__ |
| ActionButton_test.opi | Pass |
| BubbleGraph_test.opi | Pass |
| ComboBox_test.opi | Pass |
| Container_test.opi | Pass |
| Gauge_Meter_Thermometer_Tank_test.opi | Pass |
| LED_test.opi | Pass |
| TextInputWidget_test.opi | Pass |
| TextUpdate_test.opi | Pass |
| XYGraph_test.opi | Pass |

**Comment by berryma4** [comment]
Closing ticket, because the punch list is done.  If any new issues come up, report under 4.1.x and regression tests should be added.

Thank you everyone!
