### ISSUE TITLE
Improve CS-Studio for users

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#1610]
We talked a lot about how the 4.2 release didn't offer a lot for users.  Can we use this ticket to collect ways in which we can improve the user experience for 4.3?
- [x] #1568 Open OPI perspective when editing OPIs
- [x] #1607 BOY confirm dialog
- [x] #1594 EDM and ADL features
- [x] #1521 Double click in data-browser search view
- [ ] #1853 Spurious 'dirty editor' in data-browser
- [x] #1854 Disable autoscale when zooming and panning data-browser
- [ ] #1900 Process Variable context menu from probe

Feel free to close the ticket if you don't think it's helpful.
